export default {
    SYSTEM_ALERT: 'SYSTEM_ALERT',
    INITIAL_DATA_CHANGED: 'INITIAL_DATA_CHANGED',
    CARD_CREATED: 'CARD_CREATED',
    OPEN_CREDENTIAL: 'OPEN_CREDENTIAL',
    RELOAD_CREDENTIALS: 'RELOAD_CREDENTIALS',
    CREDENTIAL_CREATED: 'CREDENTIAL_CREATED',
    RIGHT_CLICK: 'RIGHT_CLICK',
    FOLDER_CREATED: 'FOLDER_CREATED',
    FOLDER_CREATION_ABORTED: 'FOLDER_CREATION_ABORTED'
}
